config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get 'users/create'
  root 'users#download'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    collection do
      post :mass_create
      get :download
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery with: :null_session
  def mass_create
    users = []
    params[:users].each do |u|
      users << User.create(user_params(u))
    end
    render json: {result: users.collect do |u|
      if u.valid?
        {u.name => :ok}
      else
        {u.name => u.errors}
      end
    end}
  end

  def download
    authenticate_account!
  end

  def index
    authenticate_account!
    @users = User.all
    respond_to do |format|
      format.xlsx
    end
  end

  private
  def user_params params
    params.permit(:name, :email, :creation_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserDb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/download.html.erb
<div class="container">
	<div class="card users-download-card p-4 m-4">
		<h1 class="text-center">Base de datos <small>(<%= User.all.count %> usuarios)</small></h1>
		<div class="text-center">
			<%= link_to 'Descargar Excel', users_path(format: :xlsx), class: 'btn btn-primary mt-4' %>
		</div>
		<div class="text-center"> 
			<%= link_to('Cerrar Session', destroy_account_session_path, method: :delete, class: 'btn btn-secondary mt-4') %>        
		</div>
	</div>
</div>